# Generated by Django 5.0.3 on 2024-03-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='content',
        ),
    ]
